### ISSUE TITLE
Not able login

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/mobile#22]
Here is Xcode log

```
2021-02-19 16:29:41.206303+0530 Runner[57896:358971] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: Class ‘_TypeError’ has no instance getter ‘statusMessage’.

Receiver: Instance of '_TypeError’

Tried calling: statusMessage

#0 Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)

#1 LoginViewModel.login (package:frappe_app/views/login/login_viewmodel.dart:99:22)

#2 Login.build.. (package:frappe_app/views/login/login_view.dart:100:48)
```

**Comment by sumitbhanushali** [comment]
@mohsinalimat Thanks for the log, I checked the issue, actually API response has been changed in latest develop branch of Frappe Framework, hence you are unable to login.

**Comment by mohsinalimat** [comment]
@sumitbhanushali Most welcome bro, I have to contribute more and more to ERPNext and Frappe.

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/34
